version: '3'
volumes:
  bundle:
  postgresql_data:
services:
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 7601:5432
  app:
    build: .
    depends_on:
      - db
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 7600 -b '0.0.0.0'"
    restart: always 
    env_file:
      - .env
    volumes:
      - bundle:/usr/local/bundle
      - ./:/app
    ports: 
      - 7600:7600
  